#!/usr/bin/env python3
"""Compile public-domain Natural Earth 1:50m land/lakes for offline radar maps.

Usage: python scripts/build_world_map.py ne_50m_land.geojson ne_50m_lakes.geojson
No receiver settings or household coordinates are inputs.
"""
import argparse
import hashlib
import json
from pathlib import Path


def compile_sources(filenames):
    points, rings, sources = [], [], []
    for water, filename in enumerate(filenames):
        raw = filename.read_bytes()
        sources.append((filename.name, hashlib.sha256(raw).hexdigest()))
        for feature in json.loads(raw)['features']:
            geometry = feature['geometry']
            if geometry['type'] == 'Polygon':
                polygons = [geometry['coordinates']]
            elif geometry['type'] == 'MultiPolygon':
                polygons = geometry['coordinates']
            else:
                raise ValueError(f'Unsupported geometry: {geometry["type"]}')
            for polygon in polygons:
                for ring in polygon:
                    coords = []
                    for lon, lat, *_ in ring:
                        point = (round(lat * 10000), round(lon * 10000))
                        if not coords or coords[-1] != point:
                            coords.append(point)
                    if not coords:
                        continue
                    if coords[-1] != coords[0]:
                        coords.append(coords[0])
                    if len(coords) < 4:
                        continue
                    if any(abs(a[1] - b[1]) > 1800000 for a, b in zip(coords, coords[1:])):
                        raise ValueError('Source ring crosses longitude seam; split before compiling')
                    rings.append((len(points), len(coords),
                                  min(p[0] for p in coords), max(p[0] for p in coords),
                                  min(p[1] for p in coords), max(p[1] for p in coords), water))
                    points.extend(coords)
    return points, rings, sources


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('land', type=Path)
    parser.add_argument('lakes', type=Path)
    args = parser.parse_args()
    points, rings, sources = compile_sources((args.land, args.lakes))
    text = '''// Generated by scripts/build_world_map.py. Made with Natural Earth.
// Public domain; source hashes and regeneration: docs/MAP_DATA.md.
#pragma once
#include <cstdint>
namespace ui::map::worldData {
struct Point { int32_t lat, lon; };
struct Ring { uint32_t first, count; int32_t minLat, maxLat, minLon, maxLon; uint32_t water; };
constexpr Point points[] = {
'''
    text += ''.join('  {' + ', '.join(map(str, p)) + '},\n' for p in points)
    text += '};\nconstexpr Ring rings[] = {\n'
    text += ''.join('  {' + ', '.join(map(str, r)) + '},\n' for r in rings)
    text += '};\n}  // namespace ui::map::worldData\n'
    output = Path(__file__).resolve().parents[1] / 'include/data/world_map.h'
    output.write_text(text)
    print(f'{len(points)} points, {len(rings)} rings, '
          f'{len(points) * 8 + len(rings) * 28} bytes in flash')
    for source, digest in sources:
        print(source, digest)


if __name__ == '__main__':
    main()
